### ISSUE TITLE
actions.change does not actually anything change until complete re-render

### ISSUE THREAD

**Issue by Rhywden** [davidkpiano/react-redux-form#191]
I'm using Meteor and parts of the dataflow are async as a result. For instance, if I want to edit an existing document, I need to do `store.dispatch(actions.change('model.foo', async_result.value));`

This works fine for the first render of the component. However, if the component is not unmounted afterwards, I can dispatch any changes I want, the form won't reflect any changes.

I can see the action 'rrf/change' in ReduxDevtools, I can see that the state of the store has indeed changed - but the view is not changed.

**Comment by davidkpiano** [comment]
What version of RRF are you on? This has been fixed as of `0.12.x`.

**Comment by Rhywden** [comment]
0.9.14, or so it seems. Hrmh. And I did an `npm update` five minutes ago. Will have to see why it doesn't pull in the newer version.

**Comment by Rhywden** [comment]
Okay, I still don't know why npm didn't do the one job it's supposed to do but manually bumping the version in package.json seems to have done the trick.

One more thing to look out for, or so it seems. Thanks for the prompt reply!
