### ISSUE TITLE
performances in a medium size form

### ISSUE THREAD

**Issue by keown** [davidkpiano/react-redux-form#262]
hi,
i've this form that uses material-ui and react-redux-form

https://gist.github.com/keown/79016d8129fe69f378489fdf7342dd2d

i know it's pretty complex but when i write in one fo the fields everything become terribly slow and unresponsive. am i doing something wrong or it's "normal" ?

**Comment by davidkpiano** [comment]
Can you put a sample form on www.esnextb.in ?

Also, you can try only updating on blur:

```js
const MaterialField = createFieldClass({
  'TextField': controls.text
}, {
  updateOn: 'blur'
});
```

This should provide a significant performance boost. It's hard to pinpoint exactly where the performance issues are because you're using more libraries on top of RRF (and those might be the bottleneck). V1 will address performance heavily.

**Comment by keown** [comment]
this code seems to solve the performance issue 

```jsx
const MaterialField = createFieldClass({
  'TextField': controls.text
}, {
  updateOn: 'blur'
});
```

but unfortunately it breaks the material-ui `TextField`

defining `MaterialField` this way seems ok

```jsx
const MaterialField = createFieldClass({
  'TextField': (props) => ({
    name: props.name,
    onChange: props.onChange
  }, {
    updateOn: 'blur'
  })
})
```

but the formReducer tell me the form is valid even if it's not, same problem of #241

**Comment by compact** [comment]
My forms also render very slowly. From CPU profiling, the functions taking up most of the time are `flatten` and `findKey` inside `getFormStateKey`. It looks like the entire state gets flattened every time the form state has to be retrieved, when the form state is not cached. The Redux state in my app is a large deeply nested object, and flatten is an expensive operation on it.

@davidkpiano, will the new API that you describe in this comment solve part of this issue?
https://github.com/davidkpiano/react-redux-form/issues/163#issuecomment-214862616

**Comment by davidkpiano** [comment]
> will the new API that you describe in this comment solve part of this issue?

Yes it will. However, I'll try to make a patch that improves performance for `flatten` and `findKey`, because `getFormStateKey` _should_ be cached.

**Comment by davidkpiano** [comment]
@keown @compact I just pushed out a commit that refactors `getFormStateKey()`, with these optimizations:

- `flatten` is no longer used in this function
- `findKey` (lodash) is no longer used in this function
- A breadth-first object key traversal is done first, as `formReducer`s are most likely on the top-level of the state, rather than deep in the leaf nodes.
  - If the `formReducer` key is found, return early.
  - If the key represents a state slice that's an object (and not an array/primitive), store it as a _candidate_ for searching.
- Each candidate key is then searched recursively for the `formReducer`, which will exit early if it is found.

Can you please verify that this alleviates performance issues? You can do so by `git clone`-ing this repo and running `npm install && npm link && npm run build:watch` or by specifying the git URL in your `package.json` dependencies for `react-redux-form`.

**Comment by keown** [comment]
@davidkpiano doesn't fix the problem for me. it seems slower :-(

by the way this solution is ok for me but i need to find out exactly all params i need to map to make everything work correctly, including validations

```js
const MaterialField = createFieldClass({
  'TextField': (props) => ({
    name: props.name,
    onChange: props.onChange
  }, {
    updateOn: 'blur'
  })
})
```
 can you help me with that? i gave a look to the source code but i can't really understand what's needed.

**Comment by davidkpiano** [comment]
@keown Really? It shouldn't be... hmm. Anyway, add this:

```diff
const MaterialField = createFieldClass({
  'TextField': (props) => ({
    name: props.name,
    onChange: props.onChange,
+   onBlur: props.onBlur,
  }, {
    updateOn: 'blur'
  })
})
```

**Comment by compact** [comment]
@davidkpiano That fixed the performance issue on a small form, thanks! I'll test with a large form (hundreds of fields) and update you if there are any problems.

**Comment by davidkpiano** [comment]
V1 introduces a ton of performance enhancements, with improved batching strategies, tweaked `shouldComponentUpdate` for `<Form>, <Field>, <Control>`, and the ability to ignore certain actions via the `ignore={['focus', 'blur']}` prop. Now in `@beta`!
