### ISSUE TITLE
Cursor position not remembered

### ISSUE THREAD

**Issue by MrBlenny** [davidkpiano/react-redux-form#355]
Every time I make a change to a field the text cursor is added to end of the field. This means you can't easily edit text inputs.

![alt tag](https://www.dropbox.com/s/9olamkoy6wctcgp/Cursor%20position%20changing%20react-redux%20form.gif?dl=1)

Component code:
``` js
<Field model="changes.model.commitSummary">
  <input className={styles.input} type="text" placeholder="Summary"/>
</Field>
```

Reducer code:
``` js
import {
  SELECTED_FILE_CHANGE,
  TOGGLE_ALL_CHANGED_FILES
} from '../actions/changes';

import { formReducer, modeled } from 'react-redux-form';

import {assignAll} from '../helpers/reducerUtils.js'

const initialState = {
  model: {
    files: [
      {
        name: 'asfasfasfasf1',
        selected: true
      },
      {
        name: 'asfasfasfasf2',
        selected: true
      },
      {
        name: 'asfasfasfasf3',
        selected: false
      },
      {
        name: 'asfasfasfasf4',
        selected: false
      },
      {
        name: 'asfasfasfasf5',
        selected: false
      },
      {
        name: 'asfasfasfasf6',
        selected: true
      },
      {
        name: 'asfasfasfasf7',
        selected: true
      },
      {
        name: 'asfasfasfasf8',
        selected: true
      },
      {
        name: 'asfasfasfasf9',
        selected: false
      },
    ],
    toggleAll: false,
    selectedFile: {},
    
    commitSummary: '',
    commitDescription: ''
  }
}


const CommitChanges = (state, action) => {
  switch (action.type) {
    case SELECTED_FILE_CHANGE:
      return {...state,
        selectedFile: action.payload
      }
    case TOGGLE_ALL_CHANGED_FILES:
      return {...state,
        files: assignAll(state.files, 'selected', action.payload.value)
      }
    default:
      return state;
  }
}

export default function (state = initialState, action) {
  return {
    model: modeled(CommitChanges, 'changes.model')(state.model, action),
    form : formReducer('changes.form')(state.form, action)
  }
}

```

**Comment by davidkpiano** [comment]
I can't reproduce this behavior with a normal text input. Are you formatting/masking the text input?

Can you also throw this up on www.esnextb.in ?

**Comment by MrBlenny** [comment]
Do you have a basic esnextbin setup I can modify?

**Comment by davidkpiano** [comment]
Yes, go ahead and copy this for v1.0-beta: https://esnextb.in/?gist=15e9350ba0e68fd001436d20502a9c69

**Comment by davidkpiano** [comment]
I now can reproduce this. Fix coming up.

**Comment by davidkpiano** [comment]
This has been fixed, and will be out in the next `@beta`. To confirm, run `npm run examples`.

**Comment by MrBlenny** [comment]
This is still not working in V0.14.6.
Is the fix in the beta ready to go into one of the main releases? Any reason I shouldn't run the beta in production?

**Comment by davidkpiano** [comment]
@MrBlenny I'm just finishing docs! The beta is stable (twice as many unit tests as 0.14.x, and it reuses most of the same tests anyway). I just want to test it in a complex production app (dogfooding!) before releasing it.
