### ISSUE TITLE
Performance Issue on only 1st item of collection

### ISSUE THREAD

**Issue by ozum** [davidkpiano/react-redux-form#382]
## Version
`v1.0.0`: No problem
`v1.0.0-beta.1` to `v1.0.0-beta.8`: Problem exists. (High usage for every key press on 1st line) 
`v1.0.0-beta.9`: Much better, but still exists. (High usage 1 out of 5 key presses on 1st line)

## Problem
Performance issue. When using collection items,  first item is slow. Remaining are OK.

## Details
I feel perceivable slowness when updating collection items. This happens both `updateOn="change"` and `updateOn="blur"`.

Strangely it happens only first item of the collection but not remaining items.

I use Chrome FPS meter to see what happens and attached video of FPS meter to show the issue. Please see FPS meter shows high usage when updating 1st line, but not second line.

### updateOn="change" video
![2016-09-03_10-19-55-1](https://cloud.githubusercontent.com/assets/1497060/18223553/8156b384-71c3-11e6-9909-fbbe74e034a1.gif)

### updateOn="blur" video
![2016-09-03_10-28-47](https://cloud.githubusercontent.com/assets/1497060/18223556/8d734538-71c3-11e6-90f7-262455a37905.gif)

**Comment by davidkpiano** [comment]
Can I see the code for this? It looks like editing the first row also affects the text at the end, which could be inadvertently contributing to the slowness.

Excellent reporting, by the way!

**Comment by davidkpiano** [comment]
I've added some performance enhancements and a stress-test example in this commit: 685c845d4e0d869cce88043c80037be14ee9b0c4 FYI. Omitting `propTypes` from the components when not in `NODE_ENV=production` seems to increase performance.

Other things that can be done:
- `updateOn="blur"` (of course)
- `ignore={['focus', 'blur']}` if your app doesn't care about those events
- keeping `map(rows => ...)` in your form's `this.state`, otherwise, that `rows => ...` function will get called on _every render_.

**Comment by ozum** [comment]
(I updated second video with more clear one)

My point is not general performance issue. My point is performance difference between 1st item and remaining items. All items share same conditions (as expected in a loop), but first line is slow, while other rows' performance are excellent for same conditions. I expect either all rows are slow or all rows are fast.

Both for `updateOn="blur` and `updateOn="change"`, see what happens for every key press (even for `updateOn="blur`). Every key press for the first row results in dramatic resource usage such that you can tell when I press a key just by looking FPS meter. However for other rows, key presses does not change graph line in FPS meter.

You can access whole code on repo `git@bitbucket.org:fortibase/item-list.git`, commit `3eefc05`.

**Comment by davidkpiano** [comment]
I pulled down the repo and tried to recreate, but it seems to be running at a smooth 60fps for all fields:

![recece](https://cloud.githubusercontent.com/assets/1093738/18226808/b683420e-71df-11e6-9aa1-7a9983282fcf.gif)

**Comment by ozum** [comment]
It seems so. I tried again in 3 different machines (OS X, Windows XP, Windows 10 all served by OS X) and I encountered same issue.

If possible, could you please try with another machine?

**Comment by ozum** [comment]
Just realized that `v1.0.0` is OK.

**Comment by davidkpiano** [comment]
Okay awesome! Please let me know if there are any other performance regressions. Also, do you mean `v1.0.0` as in directly from the `master` branch?

**Comment by ozum** [comment]
@davidkpiano please reopen this issue at least until you try it on another machine.

By `1.0.0`, I mean the version from npm. Command: `npm install react-redux-form@1.0.0`

P.S. As you remember, this version confused me, which I asked in another case, because I assume `1.0.0` is greater and later than betas. However you are developing new betas after `1.0.0`.

**Comment by ozum** [comment]
Latest report. I also updated (first message according to this).

For this particular problem:
`v1.0.0`: There is no problem.
`v1.0.0-beta.1` to `v1.0.0-beta.8`: Problem exists. (High usage for every key press on 1st line)
`v.1.0.0-beta.9`: Performance greatly enhanced, but still exists. (High usage 1 out of 5 key presses on 1st line)

**Comment by davidkpiano** [comment]
@ozum Can you verify that this issue still exists with the latest RRF? #427 should have addressed this holistically.

**Comment by davidkpiano** [comment]
Closing due to inactivity - this should already be fixed. 👍

**Comment by ozum** [comment]
Hi David,

I'm abroad. I'll look into that when I'm back. I will message you to reopen this if issue still exists.
