### ISSUE TITLE
asyncValidators & validators not working together

### ISSUE THREAD

**Issue by ulyr** [davidkpiano/react-redux-form#993]
### The Problem
asyncValidator functions not triggering if validators are declared

### Steps to Reproduce
Have asyncValidator and validators both in the same Control / Field component

### Expected Behavior
Have them both work according to what can be seen in the documentation -
https://davidkpiano.github.io/react-redux-form/docs/guides/validation.html

### Actual Behavior
Only validators functions are triggered

### Reproducible Code Example
https://codepen.io/anon/pen/dVxYEy

**Comment by davidkpiano** [comment]
Fixed in 
https://github.com/davidkpiano/react-redux-form/commit/3de4239803c249c04b7678e07b8cc13b459c6a1c but you have to make sure that `validateOn` is the same as `asyncValidateOn`. The default for `asyncValidateOn = 'blur'` so you have to change that to `asyncValidateOn="change"`.

**Comment by durz** [comment]
Has this been released? It's still an issue as reported in #1013.

**Comment by davidkpiano** [comment]
Just published in 1.16.1
